### ISSUE TITLE
Unable to Build Project (using `.NET SDK 6.0`)

### ISSUE THREAD

**Issue by lwthatcher** [JimThatcher/sport-streamer#8]
# Unable to Build Project

## Overview:
When following steps from the README, upon running the publish command several errors occur stating that multiple .NET external dependencies were unable to be resolved.

> So far this has only been verified with the .NET 6.0 SDK, as this is the version specified in the README.

## Description:
I downloaded and installed the .NET 6.0 SDK using the link provided in the *Build it yourself* section of `README.md` using the provided installation wizard. After verifying the installation was successful, I ran the following command:
```
dotnet publish -c Release
```
This resulted in the following errors:
```
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
C:\---\sport-streamer\sport-streamer.csproj : error NU1100: Unable to resolve 'Lib.AspNetCore.ServerSentEvents (>= 8.1.0)' for 'net6.0'.
C:\---\sport-streamer\sport-streamer.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.SpaProxy (>= 6.0.1)' for 'net6.0'.
C:\---\sport-streamer\sport-streamer.csproj : error NU1100: Unable to resolve 'Microsoft.EntityFrameworkCore.InMemory (>= 6.0.8)' for 'net6.0'.
C:\---\sport-streamer\sport-streamer.csproj : error NU1100: Unable to resolve 'Microsoft.EntityFrameworkCore.Sqlite (>= 6.0.8)' for 'net6.0'.
C:\---\sport-streamer\sport-streamer.csproj : error NU1100: Unable to resolve 'Microsoft.OpenApi (>= 1.3.2)' for 'net6.0'.
C:\---\sport-streamer\sport-streamer.csproj : error NU1100: Unable to resolve 'System.IdentityModel.Tokens.Jwt (>= 6.22.0)' for 'net6.0'.
C:\---\sport-streamer\sport-streamer.csproj : error NU1100: Unable to resolve 'System.IO.Ports (>= 6.0.0)' for 'net6.0'.
  Failed to restore C:\---\sport-streamer\sport-streamer.csproj (in 426 ms).
```
### Setup:
- Run on a Windows 11 laptop.
- Project cloned from GitHub using *(master)* branch.
- Working environment was within Visual Studio Code.
- Command has been run using **powershell**, **cmd**, and **bash** - all with the same result.
- Using `.NET SDK v6.0`

## Remediation Attempts:
- [x] Close *Visual Studio Code* and reopen, allowing project/cache to reload
- [x]  Run command outside of *Visual Studio Code*
- [x] Try using different versions of the .NET SDK
  - [x] `v7.0`
  - [ ] `v5.0`
- [x] Download and attempt with .NET SDK VSCode integration 
  > **Note:** the VSCode integration _is_ the .NET SDK coding pack. Duplicate check-list item has been removed.

**Comment by lwthatcher** [comment]
## Specifying Version:
the .NET SDK by default uses a _side-by-side_ model, allowing multiple version builds to exist simultaneously.
This may have to be forced or overridden to properly test using different versions.
There are multiple ways to achieve this:
  - [x] ~~attempt different version(s) using the `--roll-forward` argument~~
    > **Note:** `--roll-forward` command not available in `build` command
  - [ ] specify version using `--runtime` command
  - [ ]  specify version in `globals.json`
  - [ ] specify version using `<TargetFramework>` tag
  - [x] in `publish`  use `--ucr` (use current release) argument
    > not available in `build` command

**Comment by lwthatcher** [comment]
While searching similar errors, there is evidence to suggest that using .NET SDK version `5.0` might fix this problem, it is however listed as *unsupported* on the .NET downloads page. This also means there is no download wizard, thus requiring a manual installation.

In the interest of other future end-users, I would like to avoid this if possible. I will attempt a few other workarounds before resulting to the `5.0` SDK.

**Comment by lwthatcher** [comment]
# Issue Resolved
The issue turned out to be that the .NET SDK did not have NuGet (or anything else) listed as a source, so lacked a way to download dependencies.  Adding NuGet as a source fixed the build issues, and it is able to publish correctly now.

## Including Sources
To add NuGet as a source, one extra command is required *before* publishing:
```
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
```
Note that this only needs to be run *once* prior to publishing. After this it should have access to the NuGet repository and be automatically able to install missing dependencies.

For further details on including sources in your .NET SDK environment, please refer to the `dotnet` [documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source).

## Next Steps
The good news is this is not a problem with `dotnet` or require unsupported versions. Future users may still encounter this problem, so the README will need to be updated; but that should be included as its own issue.

**Closing Issue**

**Comment by JimThatcher** [comment]
Thank you for reporting this issue, and for doing the investigation to find a resolution.
